name: Release Step (Build Image)
run-name: |
  release (${{inputs.flavor}}) - build image with ${{inputs.uno-middleware}} on ${{inputs.base-tag}} [${{github.ref_type == 'branch' && 'nightly' || 'stable'}}, ${{github.ref_name}}]

on:
  workflow_call:
    inputs:
      flavor:
        type: string
        required: true
      uno-middleware:
        type: string
        required: true
      base-tag:
        type: string
        required: true
      tags-config:
        type: string
        required: true
      flavor-config:
        type: string
        required: true

concurrency:
  group: release-build-${{github.ref}}-${{inputs.flavor}}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone uno
        uses: actions/checkout@v4
        with:
          path: src/uno
          submodules: true

      - name: Clone ARM support files
        uses: actions/checkout@v4
        with:
          repository: mentalsmash/uno-ci-arm
          token: ${{ secrets.UNO_CI_ARM_PAT }}
          ref: master
          path: src/uno-ci-arm
        if: inputs.uno-middleware == 'uno_middleware_connext'

      - name: Configure build
        id: config
        run: |
          # Configure ARM support
          case '${{ inputs.uno-middleware }}' in
            uno_middleware_connext)
              # Copy available wheels, the right one will be picked up by the Dockerfile
              cp src/uno-ci-arm/resource/rti/rti.connext-*-linux_*.whl \
                 src/uno
              ;;
          esac

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract image metadata
        id: meta-github
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}-test
          tags: ${{ inputs.tags-config }}
          flavor: ${{ inputs.flavor-config }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Log in to GitHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push test images
        uses: docker/build-push-action@v5
        with:
          file: src/uno/docker/Dockerfile
          tags: ${{ steps.meta-github.outputs.tags }}
          labels: ${{ steps.meta-github.outputs.labels }}
          annotations: ${{ steps.meta-github.outputs.annotations }}
          push: true
          context: src/uno
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=${{ inputs.base-tag }}
            UNO_MIDDLEWARE=${{ inputs.uno-middleware }}

