name: release

on:
  push:
    # Consider any tag without a / to be a release tag
    # Use / to denote non-release tags.
    tags:
      - '*'
      - '!*/**'

concurrency:
  # Don't run job in parallel
  group: ${{ github.workflow }}

jobs:
  build:
    strategy:
      matrix:
        base-image: ["ubuntu:22.04", "ubuntu:24.04"]
        uno-middleware: [uno.middleware.native]
        include:
          - base-image: ubuntu:22.04
            uno-middleware: uno_middleware_connext
    uses: ./.github/workflows/build_and_test.yml
    secrets: inherit
    with:
      base-image: ${{ matrix.base-image }}
      uno-middleware: ${{ matrix.uno-middleware }}

  build_arm64:
    strategy:
      matrix:
        base-image: ["ubuntu:22.04"]
        uno-middleware: [uno_middleware_connext]
        include:
          - base-image: ubuntu:24.04
            uno-middleware: uno.middleware.native
    uses: ./.github/workflows/build_and_test_arm64.yml
    secrets: inherit
    with:
      base-image: ${{ matrix.base-image }}
      uno-middleware: ${{ matrix.uno-middleware }}

  build_docker:
    needs: [build, build_arm64]
    uses: ./.github/workflows/push_images_release.yml
    secrets: inherit

