name: Install Test
run-name: |
  install test [${{github.ref_type == 'branch' && 'nightly' || 'stable'}}, ${{github.ref_name}}${{github.ref_type == 'branch' && '@' || ''}}${{github.ref_type == 'branch' && github.sha || ''}}]

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: Platforms to test (JSON array)
        type: string
        default: '["amd64", "arm64"]'
      tag:
        description: Image tag to test
        type: string
        default: mentalsmash/uno:latest

concurrency:
  group: install-test-default-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        platform: ${{ fromJson(inputs.platforms) }}
        install-rti-license: [true, false]
    uses: ./.github/workflows/_install_test.yml
    secrets: inherit
    with:
      tag: ${{ inputs.tag }}
      platform: ${{matrix.platform}}
      install-rti-license: ${{matrix.install-rti-license}}
